defaultElo: 1200
arenaCountDownTime: 5
messages:
  arenaCountDown: "&eStarting in {time}&ls&e..."
  duelStart: "&eDuel Started"
  gameEnded: "&eThe game {name} has ended!"
  setSpawnPoint: "&eSet spawn point to {location}."
  reloadConfig: "&eReloaded config."
  startingSetUp: "&eStarting the setup."
  positionNotSet: "&cError: Position {position} is not set."
  createArena: "&eYou've created the arena!"
  playerDoesNotExist: "&cThe player {name} doesn't exists."
  setPosition: "&eSet position-{number} to &7({location})"
  consoleHasNoStats: "&cConsole has no stats."
  playerLeaveGame: "&c{player} left the game."
  duelEnd: "&cThe duel has ended!"
  kickMessage: "&aKicked"
  yourIngame: "&cYou cannot do that while ingame"
  ingame: "&c{name} is already in a game."
  noPendingRequest: "&cYou don't have a incoming duel request with {name}"
  alreadyHavePendingRequest: "&cYou already have a pending duel request with {name}"
  incomingDuelRequest: "&e{name} wants to duel you"
  yesHoverMessage: "&aClick to accept duel"
  yesText: "&a[ACCEPT CLICK]"
  arenaCreateFail: "&cCorrect Usage: /createArena <name> <author>"
  noHoverMessage: "&cClick to decline duel"
  noText: "&c[DECLINE CLICK]"
  joinedQueue: "&cYou've joined the queue {game}"
  leftQueue: "&cYou've left the queue {game}"
  notEnoughWins: "&cYou don't have enough unranked wins you must have at least 10."
  foundPlayer: "&eFound player {name} in {game} queue"
  sentDuelRequest: "&eSent duel request to {name}"
  declinedDuelRequest: "&eYou've declined the duel request from {name}"
  declineDuelRequest: "&e{name} has declined the duel request from you"
  acceptedDuelRequest: "&eAccepted the duel request from {name}"
  acceptDuelRequest: "&e{name} has accepted the duel request"
  eloTopAmount: 3
  eloTopList:
  - "&f&l=======[Elo Top]======="
  - "&e&l{number}. &e{name} &e{elo} elo"
  errorNoPermission: "&cYou don't have the permission {permission}"
  rankedDuelWinnerMessages:
  - "&8&m---------------------------------"
  - "&6{winner} &7has won the duel"
  - "&6{winner} &7had {winner_health} health left"
  - "&6{loser} &7had {loser_health} health left"
  - "&6{loser} &7{elo_loss}"
  - "&6{winner} &7{elo_gain}"
  - "&8&m---------------------------------"
  unRankedDuelWinnerMessages:
  - "&8&m---------------------------------"
  - "&e{winner} has won the duel"
  - "&e{winner} had {winner_health} health left"
  - "&e{loser} had {loser_health} health left"
  - "&8&m---------------------------------"
  playerStats:
  - "&8&m---------------------------------"
  - "&eUsername: &b{name}"
  - "&e&lElo"
  - "  &eDebuff: &b{ranked_refill_elo}"
  - "  &eNo Debuff: &b{ranked_no_debuff_potion_elo}"
  - "&e&lDeaths"
  - "  &eDebuff: &b{ranked_debuff_potion_deaths}"
  - "  &eNo Debuff: &b{ranked_no_debuff_potion_deaths}"
  - "&e&lKills"
  - "  &eDebuff: &b{ranked_no_debuff_potion_kills}"
  - "  &eNo Debuff: &b{ranked_no_debuff_potion_kills}"
  - "&eCredits: &b{credits}"
  - "&eTotal Kills: &b{total_kills}"
  - "&eTotal Deaths: &b{total_deaths}"
  - "&eTotal KDR: &b{total_kdr}"
  - "&eGlobal Elo: &b{global_elo}"
  - "&eRanked Wins: &b{ranked_wins}"
  - "&eUnranked Wins: &b{unranked_wins}"
  - "&8&m---------------------------------"
permissions:
  setSpawn: "duels.setSpawn"
  reloadDuels: "duels.reload"
  setArenaSpawnPoint: "duels.addArenaSpawnPoint"
  setupArena: "duels.setup"
joinMessageList:
- " "
- "Welcome {player}"
- " "
spawnScoreboardTitle: "Practice"
spawnScoreboardLines:
- "Line1"

soupHealAmount: 0
queueItemName: "&f{ladder}"
queueItemLore:
- "&fIn Queue: &a{in_queue_amount}"
- "&fIn Game: &a{in_game_amount}"
duelMenus:
  UNRANKED_DEBUFF_POTION:
    type: POTION
    name: "&3Debuff"
    loreList:
    - "&7Click to do unranked duel"
  UNRANKED_NO_DEBUFF_POTION:
    type: POTION
    name: "&3No Debuff"
    loreList:
    - "&7Click to do unranked duel"
  UNRANKED_MCSG:
    type: STONE_SWORD
    name: "&3MCSG"
    loreList:
    - "&7Click to do unranked duel"
  UNRANKED_VANILLA:
    type: DIAMOND_SWORD
    name: "&3Vanilla"
    loreList:
    - "&7Click to do unranked duel"
  RANKED_DEBUFF_POTION:
    type: POTION
    name: "&3Potion Debuff"
    loreList:
    - "&7Click to do ranked duel"
  RANKED_NO_DEBUFF_POTION:
    type: POTION
    name: "&3Potion No Debuff"
    loreList:
    - "&7Click to do ranked duel"
  RANKED_MCSG:
    type: STONE_SWORD
    name: "&3MCSG"
    loreList:
    - "&7Click to do ranked duel"
  RANKED_VANILLA:
    type: DIAMOND_SWORD
    name: "&3Vanilla"
    loreList:
    - "&7Click to do ranked duel"

kits:
  RANKED_DEBUFF_POTION:
    items: []
    armor: []
  RANKED_NO_DEBUFF_POTION:
    items: []
    armor: []
  RANKED_MCSG:
    items: []
    armor: []
  RANKED_VANILLA:
    items: []
    armor: []
  UNRANKED_DEBUFF_POTION:
    items: []
    armor: []
  UNRANKED_NO_DEBUFF_POTION:
    items: []
    armor: []
  UNRANKED_MCSG:
    items: []
    armor: []
  UNRANKED_VANILLA:
    items: []
    armor: []

options:
  RANKED_DEBUFF_POTION:
    build: false
    fastHittingSpeed: false
  RANKED_NO_DEBUFF_POTION:
    build: false
    fastHittingSpeed: false
  RANKED_MCSG:
    build: false
    fastHittingSpeed: false
  RANKED_VANILLA:
    build: false
    fastHittingSpeed: false
  UNRANKED_DEBUFF_POTION:
    build: false
    fastHittingSpeed: false
  UNRANKED_NO_DEBUFF_POTION:
    build: false
    fastHittingSpeed: false
  UNRANKED_MCSG:
    build: false
    fastHittingSpeed: false
  UNRANKED_VANILLA:
    build: false
    fastHittingSpeed: false
rankedSwordName: "&aRanked Queue"
unRankedSwordName: "&aUnranked Queue"
leaveQueueItemName: "&cLeave Queue"
settingItemName: "&eSettings"