name: EmeriPractice
version: ${project.version}
main: net.emeri.practice.EmeriPractice
authors: [matt11matthew]
commands:
  duel:
  setspawn:
  stats:
  rankedmenu:
  unrankedmenu:
  elotop:
  setuparena:
  duelsreload:
  confirmcreation:
  dev:
  settingmenu:
  setarenaspawnpoint:
